"""
Extract per-band stdAtmos FITS files from the molecfit molecule_atlas_UVB-MIR.fits.

The atlas contains pre-computed per-molecule transmission spectra covering
0.29-30 micron, generated by molecfit_calctrans (LBLRTM radiative transfer)
for a standard Paranal atmosphere at zenith (airmass=1).

This script resamples onto a uniform 0.01 A grid and writes one FITS table
per photometric band, matching the format used by VIPER.
"""

import numpy as np
from astropy.io import fits
from pathlib import Path

ATLAS_PATH = Path(__file__).parent / "molecfit-calib-4.4.2/cal/molecule_atlas_UVB-MIR.fits"
OUTPUT_DIR = Path(__file__).parent

# Band definitions: name, lambda_min (A), lambda_max (A), molecules, step (A)
BANDS = {
    "K": (18000, 25000, ["H2O", "CH4", "N2O", "CO2", "CO"], 0.01),
    "L": (25000, 42000, ["H2O", "CH4", "N2O", "CO2", "O3"], 0.01),
    "M": (42000, 55000, ["H2O", "CO2", "N2O", "CO", "O3"], 0.01),
}


def make_band(atlas_lam_A, atlas_data, band_name, lam_min, lam_max, molecules, step):
    """Resample atlas data onto a uniform grid for one band."""
    sel = (atlas_lam_A >= lam_min) & (atlas_lam_A <= lam_max)
    lam_src = atlas_lam_A[sel]

    # generate at float64 then truncate to float32 like the existing files
    lam_out_f64 = np.arange(lam_min, lam_max, step, dtype=np.float64)
    lam_out = lam_out_f64.astype(np.float32)
    n = len(lam_out)

    cols = [fits.Column(name="lambda", format="E", array=lam_out)]
    for mol in molecules:
        mol_src = atlas_data[mol][0][sel].astype(np.float64)
        mol_out = np.interp(lam_out_f64, lam_src, mol_src)
        np.clip(mol_out, 0.0, 1.0, out=mol_out)
        cols.append(fits.Column(name=mol, format="E", array=mol_out.astype(np.float32)))

    hdu = fits.BinTableHDU.from_columns(cols)
    outpath = OUTPUT_DIR / f"stdAtmos_{band_name}.fits"
    fits.HDUList([fits.PrimaryHDU(), hdu]).writeto(outpath, overwrite=True)
    print(f"{outpath.name}: {n} rows, {lam_out[0]:.1f}-{lam_out[-1]:.1f} A, molecules: {molecules}")
    return outpath


def main():
    print(f"Loading atlas: {ATLAS_PATH}")
    with fits.open(ATLAS_PATH) as hdul:
        atlas = hdul[1].data
        lam_um = atlas["mlambda"][0]
        lam_A = (lam_um * 1e4).astype(np.float64)

        for band_name, (lam_min, lam_max, molecules, step) in BANDS.items():
            make_band(lam_A, atlas, band_name, lam_min, lam_max, molecules, step)


if __name__ == "__main__":
    main()
